from abc import ABC, abstractmethod


class ProviderRepository(ABC):
    @abstractmethod
    async def get(self, provider_id: int) -> dict | None: ...
    @abstractmethod
    async def get_by_slug(self, slug: str) -> dict | None: ...
    @abstractmethod
    async def insert(self, name: str, slug: str, shared_secret: str) -> dict: ...
    @abstractmethod
    async def set_status(self, provider_id: int, status: str) -> None: ...


class ConsumerRepository(ABC):
    @abstractmethod
    async def get(self, consumer_id: int) -> dict | None: ...
    @abstractmethod
    async def list_by_provider(self, provider_id: int) -> list[dict]: ...
    @abstractmethod
    async def insert(self, provider_id: int, name: str, email: str, contact_name: str | None) -> dict: ...
    @abstractmethod
    async def set_status(self, consumer_id: int, status: str) -> None: ...


class ApiRepository(ABC):
    @abstractmethod
    async def get(self, api_id: int) -> dict | None: ...
    @abstractmethod
    async def list_by_provider(self, provider_id: int) -> list[dict]: ...
    @abstractmethod
    async def insert(self, provider_id: int, name: str, slug: str, upstream_url: str) -> dict: ...
    @abstractmethod
    async def set_status(self, api_id: int, status: str) -> None: ...


class PlanRepository(ABC):
    @abstractmethod
    async def get(self, plan_id: int) -> dict | None: ...
    @abstractmethod
    async def list_by_api(self, api_id: int) -> list[dict]: ...
    @abstractmethod
    async def insert(self, api_id: int, rate_limit_policy_id: int, name: str,
                     monthly_quota: int, overage_allowed: bool,
                     overage_price: float, price_monthly: float) -> dict: ...
    @abstractmethod
    async def retire(self, plan_id: int) -> None: ...


class SubscriptionRepository(ABC):
    @abstractmethod
    async def get(self, subscription_id: int) -> dict | None: ...
    @abstractmethod
    async def get_active(self, consumer_id: int, api_id: int) -> dict | None: ...
    @abstractmethod
    async def list_by_consumer(self, consumer_id: int) -> list[dict]: ...
    @abstractmethod
    async def insert(self, consumer_id: int, api_id: int, plan_id: int) -> dict: ...
    @abstractmethod
    async def set_status(self, subscription_id: int, status: str) -> None: ...


class ApiKeyRepository(ABC):
    @abstractmethod
    async def insert(self, consumer_id: int, key_hash: str,
                     key_prefix: str, expires_at=None) -> dict: ...
    @abstractmethod
    async def revoke(self, key_id: int) -> None: ...
    @abstractmethod
    async def list_by_consumer(self, consumer_id: int) -> list[dict]: ...